substitutions:
  _APP_NAME: 'insentric-superset'

steps:

- id: 'change-docker-scripts-permissions'
  name: 'ubuntu'
  args: ['bash', '-c', 'chmod -R +x ./docker']

- id: 'build-insentric-superset-build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'lean', '-t', 'us-central1-docker.pkg.dev/insentric-root/insentric-docker/insentric-superset-build:${TAG_NAME}', '.']
  env: ['DOCKER_BUILDKIT=1']

- id: 'push-insentric-superset-build'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/insentric-root/insentric-docker/insentric-superset-build:${TAG_NAME}']

- id: 'build-init-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'    
  args: 
    - -c
    - |
      docker build \
      -t us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}-init:${TAG_NAME} \
      --target init \
      --build-arg GOOGLE_AUTH_CLIENT_SECRET=$$GOOGLE_AUTH_CLIENT_SECRET \
      --build-arg GOOGLE_AUTH_CLIENT_ID=$$GOOGLE_AUTH_CLIENT_ID \
      --build-arg SMTP_USER=$$MAILERSEND_SMTP_USER \
      --build-arg SMTP_PASSWORD=$$MAILERSEND_SMTP_PASSWORD \
      --build-arg INSENTRIC_SUPERSET_VERSION=${TAG_NAME} \
      .
  dir: '/workspace/insentric-superset'
  secretEnv: ['GOOGLE_AUTH_CLIENT_SECRET', 'GOOGLE_AUTH_CLIENT_ID', 'MAILERSEND_SMTP_USER', 'MAILERSEND_SMTP_PASSWORD']

- id: 'build-celery-worker-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'    
  args: 
    - -c
    - |
      docker build \
      -t us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}-worker:${TAG_NAME} \
      --target celery_worker \
      --build-arg GOOGLE_AUTH_CLIENT_SECRET=$$GOOGLE_AUTH_CLIENT_SECRET \
      --build-arg GOOGLE_AUTH_CLIENT_ID=$$GOOGLE_AUTH_CLIENT_ID \
      --build-arg SMTP_USER=$$MAILERSEND_SMTP_USER \
      --build-arg SMTP_PASSWORD=$$MAILERSEND_SMTP_PASSWORD \
      --build-arg INSENTRIC_SUPERSET_VERSION=${TAG_NAME} \
      .
  dir: '/workspace/insentric-superset'
  secretEnv: ['GOOGLE_AUTH_CLIENT_SECRET', 'GOOGLE_AUTH_CLIENT_ID', 'MAILERSEND_SMTP_USER', 'MAILERSEND_SMTP_PASSWORD']

- id: 'build-celery-beat-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'    
  args: 
    - -c
    - |
      docker build \
      -t us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}-beat:${TAG_NAME} \
      --target celery_beat \
      --build-arg GOOGLE_AUTH_CLIENT_SECRET=$$GOOGLE_AUTH_CLIENT_SECRET \
      --build-arg GOOGLE_AUTH_CLIENT_ID=$$GOOGLE_AUTH_CLIENT_ID \
      --build-arg SMTP_USER=$$MAILERSEND_SMTP_USER \
      --build-arg SMTP_PASSWORD=$$MAILERSEND_SMTP_PASSWORD \
      --build-arg INSENTRIC_SUPERSET_VERSION=${TAG_NAME} \
      .
  dir: '/workspace/insentric-superset'
  secretEnv: ['GOOGLE_AUTH_CLIENT_SECRET', 'GOOGLE_AUTH_CLIENT_ID', 'MAILERSEND_SMTP_USER', 'MAILERSEND_SMTP_PASSWORD']
 
- id: 'build-run-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'    
  args: 
    - -c
    - |
      docker build \
      -t us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}:${TAG_NAME} \
      --target run \
      --build-arg GOOGLE_AUTH_CLIENT_SECRET=$$GOOGLE_AUTH_CLIENT_SECRET \
      --build-arg GOOGLE_AUTH_CLIENT_ID=$$GOOGLE_AUTH_CLIENT_ID \
      --build-arg SMTP_USER=$$MAILERSEND_SMTP_USER \
      --build-arg SMTP_PASSWORD=$$MAILERSEND_SMTP_PASSWORD \
      --build-arg INSENTRIC_SUPERSET_VERSION=${TAG_NAME} \
      .
  dir: '/workspace/insentric-superset'
  secretEnv: ['GOOGLE_AUTH_CLIENT_SECRET', 'GOOGLE_AUTH_CLIENT_ID', 'MAILERSEND_SMTP_USER', 'MAILERSEND_SMTP_PASSWORD']

- id: 'push-init-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-a', 'us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}-init']

- id: 'push-worker-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-a', 'us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}-worker']

- id: 'push-beat-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-a', 'us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}-beat']

- id: 'push-run-docker-image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-a', 'us-central1-docker.pkg.dev/insentric-root/insentric-docker/${_APP_NAME}']

availableSecrets:
  secretManager:
    - versionName: projects/1025069645798/secrets/GOOGLE_AUTH_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_AUTH_CLIENT_SECRET'
    - versionName: projects/1025069645798/secrets/GOOGLE_AUTH_CLIENT_ID/versions/latest
      env: 'GOOGLE_AUTH_CLIENT_ID'
    - versionName: projects/1025069645798/secrets/MAILERSEND_SMTP_USER/versions/latest
      env: 'MAILERSEND_SMTP_USER'
    - versionName: projects/1025069645798/secrets/MAILERSEND_SMTP_PASSWORD/versions/latest
      env: 'MAILERSEND_SMTP_PASSWORD'
