#!/bin/bash
k6 run --quiet \
  ${TEST_USER:+-e TEST_USER=$TEST_USER} \
  ${TEST_USER_PASSWORD:+-e TEST_USER_PASSWORD=$TEST_USER_PASSWORD} \
  ${INSTANCE_ID:+-e INSTANCE_ID=$INSTANCE_ID} \
  ${TEST_NAME:+-e TEST_NAME=$TEST_NAME} \
  "$@"